version: '3.8'

services:
  app:
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  nginx:
    ports:
      - "8080:80"  # Change to avoid conflict with system nginx
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  db:
    volumes:
      - ./docker/mysql/prod.cnf:/etc/mysql/conf.d/my.cnf:ro
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  redis:
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  redis_data:
    driver: local
